### ISSUE TITLE
title header gets overwritten (when selecting direct message of user)

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [myleneb/theme_nin#10]
see pic:
when I select our DM communication the user's name gets onto the previous header title

happens in chromium + qupzilla
Nin v2, with last commit being on Aug 3, 2015

![del](https://cloud.githubusercontent.com/assets/642286/9118736/c3fad76a-3c72-11e5-8b89-bda297107c69.png)

**Comment by myleneb** [comment]
I think it's ok now https://github.com/myleneb/theme_nin/commit/33913db6403fcb0378e9b55f5a0d31c1704deb6d
