### ISSUE TITLE
not found theme_nin/css/profile.css

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [myleneb/theme_nin#11]
see pic below
and in my twister debug logs I see:
2015-08-06 16:37:48 ServiceConnection: file /home/USER/.twister/html/theme_nin/css/profile.css not found

using Nin v2, with last commit being on Aug 3, 2015

![bildschirmfoto vom 2015-08-06 20 01 32](https://cloud.githubusercontent.com/assets/642286/9119261/09dd3590-3c76-11e5-8c87-6c5704f9e5d0.png)

**Comment by myleneb** [comment]
I saw that. profile.css is not needed for Nin theme but is still called by javascript (I think). I'll create a blank one to avoid log alerts.

**Comment by myleneb** [comment]
Fixed https://github.com/myleneb/theme_nin/commit/23c4e6c8ae078d4352a66f8937b7ce2c94169eb0
