### ISSUE TITLE
hide compose field when not needed

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [myleneb/theme_nin#12]
I am not always in "edit mode"
when I just want to read the edit-field (where I write my messages) on top takes "useless space". 

Could the edit-field appear on demand? 
(e.g. when I click my avatar pic?)

**Comment by myleneb** [comment]
Good idea, I will add a button or something to show/hide textarea

**Comment by Erkan-Yilmaz** [comment]
more important now, after adding #14 (which disturbs me)

**Comment by myleneb** [comment]
"New post" button in left area which opens a prompt for new post, see https://github.com/myleneb/theme_nin/commit/9386ed2e6953d488a6324038328515cebb904ce2 and https://github.com/myleneb/theme_nin/commit/07733890a241aba4675b8b9fe90538d856217b18 :)
