### ISSUE TITLE
unwanted raise in post text..

### ISSUE THREAD

**Issue by erqan** [myleneb/theme_nin#13]
lines after the third are raised in post text...

![nin-v2_indent](https://cloud.githubusercontent.com/assets/12120467/9163896/fe2411ca-3f53-11e5-83b2-e1832f3b54a2.png)

**Comment by erqan** [comment]
increasing left margin of `p.post-text` or decreasing right margin of `div.post-photo` should fix it.

**Comment by myleneb** [comment]
Fixed https://github.com/myleneb/theme_nin/commit/d05f121e55f537f6fa02b3e97c9c0b6951257396
