### ISSUE TITLE
Show compose field ("New post" box) when scrolling down

### ISSUE THREAD

**Issue by lohang** [myleneb/theme_nin#14]
I would like to have a way to post a new notice when I'm scrolling down my timeline. The only way I can do it right now is scrolling back to the top of the page. Older theme nin had a compose area appearing on the left column. But This is how it looks when I scroll down in the new version:

![screenshot from 2015-08-17 13 19 06](https://cloud.githubusercontent.com/assets/5318244/9303215/251e285a-44fa-11e5-87ba-0730d28d7555.png)

However, when my browser window is not maximized, I see a "New post" window at the bottom of the page. I would like to have it - or something similar - in the normal, maximized view too : 

![screenshot from 2015-08-17 13 20 06](https://cloud.githubusercontent.com/assets/5318244/9303226/40344a16-44fa-11e5-91be-20b4b300dbaf.png)

.

**Comment by myleneb** [comment]
see https://github.com/myleneb/theme_nin/commit/ca4c33bedb97f215d15e831a77f4975cfe8fa46b

**Comment by Erkan-Yilmaz** [comment]
This is actually disturbing me :-(
I'd like this to be configurable in options.
see also #12
