### ISSUE TITLE
layout problem (input field exceeding limit, when retweeting)

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [myleneb/theme_nin#17]
see pic below:

I am using NIN v2, state from: Aug 21 13:42
firefox 40

![bildschirmfoto vom 2015-08-21 19 41 27](https://cloud.githubusercontent.com/assets/642286/9415040/dbebd29a-483c-11e5-9def-4852afcfdced.png)

**Comment by myleneb** [comment]
Fixed: https://github.com/myleneb/theme_nin/commit/76acb87ac8624d151e28f33b3acfe70cf6c79c2e
