### ISSUE TITLE
Please let us close all modals with Esc

### ISSUE THREAD

**Issue by kseistrup** [myleneb/theme_nin#22]
Please let us close all modals (if you have clicked e.g. another users profile from the timeline) by hitting the `Esc` button.

**Comment by myleneb** [comment]
ok: https://github.com/myleneb/theme_nin/commit/3b884712a64c4e6b15ad0d0cffed904b1501a92f

**Comment by kseistrup** [comment]
Sweet, thanks! :smile:

**Comment by Spheerys** [comment]
Yes yes yes !
Thanks :)
