### ISSUE TITLE
group messages: avatar missing (and thus: new item counter misplaced)

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [myleneb/theme_nin#26]
see pic1, while in original theme twister-html OK (pic2)

pic1: firefox
![nin22](https://cloud.githubusercontent.com/assets/642286/11071375/e88aa81c-87e0-11e5-87a2-f7d14925fbc9.png)

pic2: chromium 47

![chromium_orig](https://cloud.githubusercontent.com/assets/642286/11071414/03a28368-87e1-11e5-9f8b-921ef70630b9.png)

**Comment by myleneb** [comment]
I deleted avatars in group list view because it has no utility.
About numbers of new twists: it will be fixed soon.
