### ISSUE TITLE
code indentation is inconsistent

### ISSUE THREAD

**Issue by slr** [myleneb/theme_nin#7]
looks like you use tabs now. is it OK?

**Comment by myleneb** [comment]
I think all .sass files are OK with tabs now

**Comment by slr** [comment]
so we use tabs now. and now I should reconfigure my editor to not replace tabs with spaces every time when I want to work with my beloved SASS. it's uncomfortably a bit.

**Comment by myleneb** [comment]
I'm sorry I didn't think it would be important. Will you forgive?

**Comment by slr** [comment]
I may forgive you but others may not. usually it's painful issue for coders.
