### ISSUE TITLE
layout broken, after visiting the "who am I following" link

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [myleneb/theme_nin#9]
after visiting the "who am I following" (1) link:
 the search-field + the other button next to it dropped some lines (see pic)

in chromium 45.x
didn't happen with FF or Qupzilla
Nin v2, with last commit being on Aug 3, 2015

(1) http://127.0.0.1:port/following.html

![bildschirmfoto vom 2015-08-06 18 19 24](https://cloud.githubusercontent.com/assets/642286/9118584/a917c152-3c71-11e5-86f9-8b5e7ddf21dd.png)

**Comment by myleneb** [comment]
Thanks for reporting. I will investigate and hope will solve this problem (and issue #10) soon

**Comment by myleneb** [comment]
same as https://github.com/myleneb/theme_nin/issues/21
